#!/bin/bash
if [ "$1" == "info-get guestinfo.cloudinit.userdata" ] ; then
  echo "with metadata"
  exit 0
elif [ "$1" == "info-get guestinfo.cloudinit.metadata" ] ; then
  echo '{"network-interfaces":"auto lo\niface lo inet loopback"}'
  exit 0
fi
>&2 echo "No Value"
exit 1
