#!/bin/bash
if [ "$1" == "info-get guestinfo.cloudinit.userdata" ] ; then
  echo "with metadata"
  exit 0
elif [ "$1" == "info-get guestinfo.cloudinit.metadata" ] ; then
  echo '{"network-interfaces":"auto lo\niface lo inet loopback","network-config":{"version":1,"config":[{"name":"eth1","type":"physical","subnets":[{"type":"dhcp","control":"auto"}]}]}}'
  exit 0
fi
>&2 echo "No Value"
exit 1
